#!/bin/bash
apt-get update
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /operate ensure=absent force=true
puppet resource file /operate ensure=directory
cd /operate
git clone https://github.com/bengyin/8391415n-op-repo.git
cp -p /operate/8391415n-op-repo/index-op-8391415n.html /var/www/html
mv /var/www/html/index.html /var/www/html/index.html.bak
mv /var/www/html/index-op-8391415n.html /var/www/html/index.html
